export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_NEW_TASK_TO_DOM = 'ADD_NEW_TASK_TO_DOM';
export const ADD_NEW_TASK_TO_PROJECT = 'ADD_NEW_TASK_TO_PROJECT';
export const NAME_CHANGE = 'NAME_CHANGE';
export const DESC_CHANGE = 'DESC_CHNAGE';
export const DATE_CHANGE = 'DATE_CHANGE';
export const IMPORTANCE_CHANGE = 'IMPORTANCE_CHANGE';