export const ADD_NEW_PROJECT = 'ADD_NEW_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ADD_NEW_TASK_TO_DOM = 'ADD_NEW_TASK_TO_DOM';
export const ADD_NEW_TASK_TO_PROJECT = 'ADD_NEW_TASK_TO_PROJECT';
export const SET_PROJECT_ACTIVE = 'SET_PROJECT_ACTIVE';