export const FIELD_EMPTY = 'FIELD_EMPTY';
export const FIELD_TOO_SHORT = 'FIELD_TOO_SHORT';
export const FIELD_TOO_LONG = 'FIELD_TOO_LONG';
export const CONTAINS_WRONG_CHARACTERS = 'CONTAINS_WRONG_CHARACTERS';
